os: osx
osx_image: xcode14.2
language: swift
script: xcodebuild clean build test -project Movies.xcodeproj -scheme Movies -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.0,name=iPhone 13" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
